version: 0.2

env:
  variables:
    AWS_REGION: us-east-1
    ECR_REGISTRY: 045998146012.dkr.ecr.us-east-1.amazonaws.com
    ECR_REPO: brain-tasks-app
    EKS_CLUSTER: brain-cluster

phases:
  install:
    commands:
      - curl -LO https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/

  pre_build:
    commands:
      - echo Logging in to Amazon ECR
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY

      - echo Updating kubeconfig
      - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER

  build:
    commands:
      - docker build -t $ECR_REPO .
      - docker tag $ECR_REPO:latest $ECR_REGISTRY/$ECR_REPO:latest

  post_build:
    commands:
      - docker push $ECR_REGISTRY/$ECR_REPO:latest
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml
